{
  lib,
  stdenv,
  onnxruntime,
  jdk21_headless,
}:

# ONNX Runtime's Java API (ai.onnxruntime) and its JNI library, built against
# nixpkgs' onnxruntime.
#
# EliteIntel pulls the Java API from Maven, which bundles its own prebuilt
# libonnxruntime.so. sherpa-onnx already links nixpkgs' one into the process,
# and the two cannot coexist: the Maven JNI library binds to whichever
# libonnxruntime.so.1 is loaded first and then misses its symbol versions.
# nixpkgs' onnxruntime has no Java support, and enabling it upstream would
# rebuild all of ONNX Runtime, so build just the binding here.
#
# TODO: upstream as a `javaSupport` flag on nixpkgs' onnxruntime.
stdenv.mkDerivation {
  pname = "onnxruntime-java";
  inherit (onnxruntime) version src;

  nativeBuildInputs = [ jdk21_headless ];
  buildInputs = [ onnxruntime ];

  dontConfigure = true;

  buildPhase = ''
    runHook preBuild

    javac -encoding UTF-8 --release 8 -nowarn -d classes -h headers \
      $(find java/src/main/java java/src/main/jvm -name '*.java')
    if [ -d java/src/main/resources ]; then
      cp -r java/src/main/resources/. classes/
    fi
    jar cf onnxruntime.jar -C classes .

    # Normally generated by ONNX Runtime's CMake; these are all the JNI code reads.
    cat > headers/onnxruntime_config.h <<EOF
    #pragma once
    #define HAS_REALLOCARRAY
    #define ORT_VERSION "$version"
    EOF

    $CC -shared -fPIC -O2 -o libonnxruntime4j_jni.so \
      -Iinclude -Iorttraining/orttraining/training_api/include -Iheaders \
      -I${jdk21_headless.home}/include -I${jdk21_headless.home}/include/linux \
      java/src/main/native/*.c \
      -L${lib.getLib onnxruntime}/lib -lonnxruntime

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    install -Dm644 onnxruntime.jar -t $out/share/java
    install -Dm755 libonnxruntime4j_jni.so -t $out/lib
    ln -s ${lib.getLib onnxruntime}/lib/libonnxruntime.so $out/lib/libonnxruntime.so
    runHook postInstall
  '';

  meta = {
    description = "Java bindings (API jar and JNI library) for ONNX Runtime";
    homepage = "https://onnxruntime.ai";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ toasteruwu ];
    platforms = lib.platforms.linux;
  };
}
